# Generated by Django 5.1.1 on 2024-10-09 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Заголовок")),
                ("content", models.CharField(verbose_name="Содержимое")),
                (
                    "preview_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/image", verbose_name="Превью"),
                ),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("published", models.BooleanField(default=False, verbose_name="Признак публикации")),
                ("views_count", models.IntegerField(default=0, verbose_name="Счетчик просмотров")),
            ],
        ),
    ]
