# Generated by Django 5.1.1 on 2024-10-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название категории")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание категории")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, verbose_name="Название продукта")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание продукта")),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="catalog/image", verbose_name="Изображение"),
                ),
                ("price", models.FloatField(help_text="Введите цену", verbose_name="Цена")),
                ("created_at", models.DateField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateField(auto_now=True, verbose_name="Дата последнего изменения")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["name"],
            },
        ),
    ]
